
/* generated by: ControllerGenerator Wed May 18 15:20:45 CEST 2016 */
package com.niewold.r.player.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Player {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    int id;
    String name;
    String email;
    String playerpass;
    String positionOffense;
    String positionDefense;
    String positionSpecial;


    public Player() {
    }

    public Player(int id, String email, String name) {
        this.id = id;
        this.email = email;
        this.name = name;
        this.playerpass = playerpass;
        this.positionOffense = positionOffense;
        this.positionDefense = positionDefense;
        this.positionSpecial = positionSpecial;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPlayerpass() {
        return playerpass;
    }

    public void setPlayerpass(String playerpass) {
        this.playerpass = playerpass;
    }

    public String getPositionOffense() {
        return positionOffense;
    }

    public void setPositionOffense(String positionOffense) {
        this.positionOffense = positionOffense;
    }

    public String getPositionDefense() {
        return positionDefense;
    }

    public void setPositionDefense(String positionDefense) {
        this.positionDefense = positionDefense;
    }

    public String getPositionSpecial() {
        return positionSpecial;
    }

    public void setPositionSpecial(String positionSpecial) {
        this.positionSpecial = positionSpecial;
    }

    @Override
    public String toString() {
        return "Player{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", playerpass='" + playerpass + '\'' +
                ", positionOffense='" + positionOffense + '\'' +
                ", positionDefense='" + positionDefense + '\'' +
                ", positionSpecial='" + positionSpecial + '\'' +
                '}';
    }
}

